version: '8.4.3'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql-520
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: mysql-520
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  db_data:
